# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.16

executors:
  default:
    docker:
      - image: circleci/golang:1.18.3-node

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Building Plugin Bundle
          command: make dist
      - persist_to_workspace:
          root: dist
          paths:
            - "*.tar.gz"
            - "release-notes.md"
      - store_artifacts:
          path: dist

